name: CD-Frontend

on:
  push:
    branches:
      - main

jobs: 
  Setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0']
    steps:
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Npm install
        run: |
            cd Frontend/angular
            npm install
            
      - name: Build Frontend
        run: |
           cd Frontend/angular
           npx ng build

      - name: Archive Frontend build
        uses: actions/upload-artifact@v2
        with:
           name: frontend-artifact
           path: "${{ github.workspace }}/Frontend/angular/FrontendDist"
