name: Create release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:         
      - name: Create release
        run: |
          git tag v1.0.0
          git push origin v1.0.0
