name: Create Release Tag
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release Tag
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v1.0.0  # Change this to your desired tag name
          release_name: Release v1.0.0  # Change this to your desired release name
          body: 'Release notes for v1.0.0'  # Change this to your desired release notes
