name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Frontend Code
        uses: actions/checkout@v2
        with:
          path: Frontend/angular

      - name: Build Frontend
        run: |
          cd Frontend/angular
          npm install
          npm run build

  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Backend Code
        uses: actions/checkout@v2
        with:
          path: Backend/aspnet-core

      - name: Restore NuGet Packages
        run: dotnet restore Backend/aspnet-core/CompanyWebsite.sln

      - name: Build Backend
        run: |
          cd Backend/aspnet-core
          dotnet build --configuration Release

  database:
    needs: [backend]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Database Code
        uses: actions/checkout@v2
        with:
          path: Backend/database


      - name: Update Database Migration
        run: |
          cd Backend/database
          dotnet ef database update --project ../aspnet-core/CompanyWebsite.csproj --startup-project ../aspnet-core/CompanyWebsite.csproj --configuration Release

  deploy:
    needs: [frontend, backend, database]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy Backend
        run: |
          cd Backend/aspnet-core
          dotnet publish --configuration Release
          # Add your deployment steps here using the published output from the previous step
          dotnet publish -c Release -o ./myapp

      - name: Deploy Frontend to IIS
        run: |
          # Add your deployment steps here to deploy the frontend to IIS
          # Example:
          # - Copy the frontend build output to the IIS virtual directory

  create-release:
    needs: [deploy]
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0 # Replace with your desired tag name
          release_name: Release v1.0.0 # Replace with your desired release name
          draft: false
          prerelease: false
          target_commitish: ${{ github.sha }}
          body: |
            Release v1.0.0
            - Added frontend deployment to IIS
            - Added backend deployment using .NET Core CLI
            - Updated database migration
            - Created new release

          token: ${{ secrets.GITHUB_TOKEN }} 
