name: CICD

on:
  push:
    branches:
      - main

jobs: 
  Setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0']
    steps:
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Build Solution Backend
        env:
          # Accessing the secret variable
          SOLUTION_PATH: ${{ secrets.BACKEND_SOLUTION_PATH }}
        run: |
         dotnet build "${GITHUB_WORKSPACE}/${SOLUTION_PATH}"
        
      - name: Test test Backend
        env:
          # Accessing the secret variable
          TEST_PATH: ${{ secrets.BACKEND_TEST_PATH }}
        run: dotnet test "${GITHUB_WORKSPACE}/${TEST_PATH}"
        
      - name: Build Frontend
        env:
            # Accessing the secret variable
            FTEST_PATH: ${{ secrets.FRONTEND_SOLUTION_PATH }}
        run: dotnet build "${GITHUB_WORKSPACE}/${FTEST_PATH}"
    
      - name: Npm install
        run: |
            cd Frontend/angular
            npm install
            
      - name: Npm start
        id: start-app
        run: |
          cd Frontend/angular
          # Start npm start in the background
          npm start &
          # Store the PID (Process ID) of the npm start process
          start_pid=$!
          # Wait for two minutes (90 seconds)
          sleep 90
          # Kill the npm start process after two minutes
          kill$start_pid"
          
          exit_code=$?
          if [ $start_pid -eq 0 ]; then
               echo "npm start compilation was successful."
             else
               echo "npm start compilation failed with exit code $exit_code."
             fi


